### ISSUE TITLE
keychain service test

### ISSUE THREAD

**Issue by jeonghomoon** [jeonghomoon/ios-data-layer#19]
## Description
KeychainService 클래스에 대해 테스트 코드를 작성합니다.
### 요구사항
1. 테스트 환경에서 Keychain 클래스 init시 kSecAttrService 영역의 Keychain 데이터가 초기화 되어야합니다.
2. KeychainService 클래스의 CRUD에 대한 테스트 코드를 작성해야합니다.
3. notFound, unexpectedData, duplicateItem, unhandledError 각 에러에 대해 실패 테스트를 작성합니다.

## TODO
- [x] Keychain convenience init
- [x] Keychain CRUD test
- [x] Keychain Error test

## Environment
macOS: Monterey 12.5.1, Apple M1
iOS: 15.5, iPhone 13 mini
IDE: Xcode 13.4.1

Related: #15 #24
