### ISSUE TITLE
persistent service test

### ISSUE THREAD

**Issue by jeonghomoon** [jeonghomoon/ios-data-layer#31]
### 배경
- PersistentService 클래스에 대한 테스트 코드를 작성합니다.

### 요구사항
1. Keychain, UserDefaults의 identifier를 주입하기 위해 테스트 번들 identifier를 가져오는 클래스가 필요합니다. 
2. Keychain, UserDefaults의 identifier를 주입하기 위해 PersistentService 클래스의 convenience initializer를 작성해야됩니다.
3. 두 저장소 모두 테스트를 위해 저장소를 다르게 선택한 두 테스트 클래스를 만들어 테스트해야 합니다.
4. 공통된 로직은 분리 후, 프로토콜 기본 구현을 이용하여 각 테스트에 채택하여 코드를 간소화 합니다.

## TODO

- [x] BundleProvider for test
- [x] PersistentService convenience initializer for test
- [x] PersistentService default implementation protocol
- [x] KeychainStore, UserDefaultsStore Tests

## Environment
macOS: Monterey 12.5.1, Apple M1
iOS: 15.5, iPhone 13 mini
IDE: Xcode 13.4.1

Related: #29
